config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'
    resources :diaries do
    collection do
      post :confirm
    end
  end
  
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/diary.rb
class Diary < ApplicationRecord
    validates :content,     length: { in: 1..140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy] 
 
  def index
    @diaries = Diary.all
  end

  def new
    if params[:back]
      @diary = Diary.new(diary_params)
    else
      @diary = Diary.new
    end
  end
  
  def confirm
    @diary = Diary.new(diary_params)
    render :new if @diary.invalid?
  end
  
  def create
    @diary = Diary.new(diary_params)
    
    if @diary.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to diaries_path, notice: "つぶやき投稿しました！"
    else
      render 'new'
    end
  end
  
  def destroy
    @diary.destroy
    redirect_to diaries_path, notice:"つぶやきを削除しました！"
  end

  def show
    @diary = Diary.find(params[:id])
  end

  def update
    @diary = Diary.find(params[:id])
    if @diary.update(diary_params)
      redirect_to diaries_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end
  
  private
  
  def diary_params
    params.require(:diary).permit(:content)
  end
  
  # idをキーとして値を取得するメソッド
  def set_diary
    @diary = Diary.find(params[:id])
  end


end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
 def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_diaries_path
    elsif action_name == 'edit'
      diary_path
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: @diary, local: true ,url: choose_new_or_edit ) do |form| %>

  <% if @diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= @diary.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @diary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    
  <% end %>

  <div class="diary_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", diaries_path %>

app/views/diaries/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @diary, url: diaries_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @diary.content %></p>
  <%= form.submit  "登録する" %>
<% end %>
<br>

<%= form_with(model: @diary, url: new_diary_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  
  <%= form.submit "もどる", name:'back' %>
<% end %>

app/views/diaries/create.html.erb
<h1>新規投稿画面</h1>

<%= form_with(model: @diary, local: true) do |form| %>
  <div class="diary_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <%= form.submit %>
<% end %>

app/views/diaries/edit.html.erb
  <h2>つぶやきを編集する</h2>

  <%= render 'form' %>

app/views/diaries/index.html.erb
<div class="container">
 <h1>つぶやき一覧</h1>

<p><%= notice %></p>


  <% @diaries.each do |diary| %>
  <div class="col-xs-12 col-sm-6 col-md-6 diary-panel">
    <h3><%= diary.content %></h3>

      <div class="diary-links">
        <%= link_to '詳細', diary_path(diary.id), class: "btn btn-primary" %>
        <%= link_to '編集', edit_diary_path(diary.id), class: "btn btn-warning" %>
        <%= link_to '削除', diary_path(diary.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } , class: "btn btn-danger" %>
      </div>
  </div>
  <% end %>
  
</div>
<%= link_to 'つぶやき一覧画面にもどる', '/index' %>
<%= link_to '新しくつぶやく', new_diary_path %>

app/views/diaries/new.html.erb
<h1>つぶやき投稿画面</h1>

  <%= render 'form' %>

app/views/diaries/show.html.erb
<h1>新規投稿画面</h1>

<p>つぶやき: <%= @diary.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav>
    <ul class="nav nav-pills">
      <li role="presentation" class="active"><%= link_to 'HOME', '/' %></li>
      <li role="presentation"><%= link_to 'つぶやき一覧', '/diaries' %></li>
      <li role="presentation"><%= link_to '新規投稿', '/diaries/new/' %></li>
    </ul>
    </nav>

  </head>

  <body>
    <%= yield %>
  </body>
  
  <footer>
    <p>Twitter app</p>
    <p>2018/01/07    Yuki Hirabayashi</p>
  </footer>

</html>

app/views/top/index.html.erb
<%#
Top#index
%>

<h1>Twitterアプリ</h1>

<article>
    <div class="container">
        <div class="row">
           <div class="col-xs-6 col-sm-6 col-md-6">
               <%= image_tag 'character_isshi-.png' %>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
               <h3>つぶやこう！</h3>
           </div>
       
        </div>
    </div>
</article>